import { AccessoryMetadata } from "../utils/accessoryUtils.js";

export const accessories: AccessoryMetadata[] = [
  {
    type: "head",
    category: "hats",
    renderOptions: { showEars: false, showFin: false },
    name: "baseball cap",
    price: 2000000000,
    quantity: null,
    description: "Baseball cap from the punk collection",
    collection: "punk",
  },
  {
    type: "head",
    category: "hats",
    renderOptions: { showEars: false, showFin: true },
    name: "beanie",
    price: 2000000000,
    quantity: null,
    description: "Beanie from the grunge collection",
    collection: "grunge",
  },
  {
    type: "head",
    category: "hats",
    renderOptions: { showEars: false, showFin: true },
    name: "beret",
    price: 2000000000,
    quantity: null,
    description: "Beret from the artist collection",
    collection: "artist",
  },
  {
    type: "head",
    category: "hats",
    renderOptions: { showEars: false, showFin: true },
    name: "bowler hat",
    price: 2000000000,
    quantity: null,
    description: "Bowler hat from the banker collection",
    collection: "banker",
  },
  {
    type: "head",
    category: "hats",
    renderOptions: { showEars: false, showFin: true },
    name: "cowboy hat",
    price: 2000000000,
    quantity: null,
    description: "Cowboy Hat from the cowboy collection",
    collection: "cowboy",
  },
  {
    type: "head",
    category: "hats",
    renderOptions: { showEars: true, showFin: true },
    name: "hair bow",
    price: 2000000000,
    quantity: null,
    description: "Hair bow from the swimmer collection",
    collection: "swimmer",
  },
  {
    type: "head",
    category: "hats",
    renderOptions: { showEars: true, showFin: true },
    name: "halo",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "head",
    category: "hats",
    renderOptions: { showEars: false, showFin: true },
    name: "santa hat",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "head",
    category: "wigs",
    renderOptions: { showEars: false, showFin: false },
    name: "blonde wig",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "head",
    category: "wigs",
    renderOptions: { showEars: false, showFin: false },
    name: "curly wig",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "head",
    category: "wigs",
    renderOptions: { showEars: false, showFin: false },
    name: "mohawk",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "head",
    category: "hats",
    renderOptions: { showEars: false, showFin: true },
    name: "wizard hat",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "head",
    category: "hats",
    renderOptions: { showEars: true, showFin: true },
    name: "snorkel",
    price: 2000000000,
    quantity: null,
    description: "Snorkel from the snorkel collection",
    collection: "snorkel",
  },
  {
    type: "eyes",
    category: "eyewear",
    renderOptions: { showEars: true, showFin: true },
    name: "8 bit glasses",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "eyes",
    category: "eyewear",
    renderOptions: { showEars: true, showFin: true },
    name: "superhero mask",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "eyes",
    category: "eyewear",
    renderOptions: { showEars: true, showFin: true },
    name: "xr goggles",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "eyes",
    category: "eyewear",
    renderOptions: { showEars: true, showFin: true },
    name: "bug eyes",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "body",
    category: "body",
    renderOptions: {},
    name: "apron",
    price: 2000000000,
    quantity: null,
    description: "Apron from the artist collection",
    collection: "artist",
  },
  {
    type: "body",
    category: "body",
    renderOptions: {},
    name: "cardigan",
    price: 2000000000,
    quantity: null,
    description: "Cardigan from the grunge collection",
    collection: "grunge",
  },
  {
    type: "body",
    category: "body",
    renderOptions: {},
    name: "leather jacket",
    price: 2000000000,
    quantity: null,
    description: "Leather jacket from the punk collection",
    collection: "punk",
  },
  {
    type: "body",
    category: "body",
    renderOptions: {},
    name: "vest",
    price: 2000000000,
    quantity: null,
    description: "Vest from the cowboy collection",
    collection: "cowboy",
  },
  {
    type: "back",
    category: "capes",
    renderOptions: {},
    name: "superhero cape",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "wizard",
  },
  {
    type: "body",
    category: "body",
    renderOptions: {},
    name: "wizard robe",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "back",
    category: "wings",
    renderOptions: {},
    name: "wings",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "legs",
    category: "legs",
    renderOptions: {},
    name: "white pants",
    price: 2000000000,
    quantity: null,
    description: "White pants from the artist collection",
    collection: "artist",
  },
  {
    type: "legs",
    category: "legs",
    renderOptions: {},
    name: "bell bottoms",
    price: 2000000000,
    quantity: null,
    description: "Bell bottoms from the grunge collection",
    collection: "grunge",
  },
  {
    type: "legs",
    category: "legs",
    renderOptions: {},
    name: "blue jeans",
    price: 2000000000,
    quantity: null,
    description: "Blue jeans from the punk collection",
    collection: "punk",
  },
  {
    type: "legs",
    category: "legs",
    renderOptions: {},
    name: "business slacks",
    price: 2000000000,
    quantity: null,
    description: "Business slacks from the banker collection",
    collection: "banker",
  },
  {
    type: "legs",
    category: "legs",
    renderOptions: {},
    name: "cutoffs",
    price: 2000000000,
    quantity: null,
    description: "Cutoffs from the cowboy collection",
    collection: "cowboy",
  },
  {
    type: "legs",
    category: "legs",
    renderOptions: {},
    name: "swim trunks",
    price: 2000000000,
    quantity: null,
    description: "Swim trunks from the snorkel collection",
    collection: "snorkel",
  },
  {
    type: "legs",
    category: "skirts",
    renderOptions: {},
    name: "punk skirt",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "legs",
    category: "skirts",
    renderOptions: {},
    name: "rock star ruffle",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "legs",
    category: "skirts",
    renderOptions: {},
    name: "superhero stars",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "object",
    category: "object",
    renderOptions: {},
    name: "palette",
    price: 2000000000,
    quantity: null,
    description: "Palette from the artist collection",
    collection: "artist",
  },
  {
    type: "object",
    category: "object",
    renderOptions: {},
    name: "brush",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "object",
    category: "object",
    renderOptions: {},
    name: "lasso",
    price: 2000000000,
    quantity: null,
    description: "Lasso from the cowboy collection",
    collection: "cowboy",
  },
  {
    type: "object",
    category: "object",
    renderOptions: {},
    name: "pencil",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "object",
    category: "object",
    renderOptions: {},
    name: "magic wand",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "object",
    category: "object",
    renderOptions: {},
    name: "microphone",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "torso",
    category: "shirt",
    renderOptions: {},
    name: "business shirt",
    price: 2000000000,
    quantity: null,
    description: "Business shirt from the banker collection",
    collection: "banker",
  },
  {
    type: "torso",
    category: "shirt",
    renderOptions: {},
    name: "cowboy shirt",
    price: 2000000000,
    quantity: null,
    description: "Cowboy shirt from the cowboy collection",
    collection: "cowboy",
  },
  {
    type: "torso",
    category: "shirt",
    renderOptions: {},
    name: "swimsuit",
    price: 2000000000,
    quantity: null,
    description: "Swimsuit from the swimmer collection",
    collection: "swimmer",
  },
  {
    type: "torso",
    category: "shirt",
    renderOptions: {},
    name: "heart shirt",
    price: 2000000000,
    quantity: null,
    description: "Heart shirt from the grunge collection",
    collection: "grunge",
  },
  {
    type: "torso",
    category: "shirt",
    renderOptions: {},
    name: "lifeguard",
    price: 2000000000,
    quantity: null,
    description: "Lifeguard from the snorkel collection",
    collection: "snorkel",
  },
  {
    type: "torso",
    category: "shirt",
    renderOptions: {},
    name: "skull shirt",
    price: 2000000000,
    quantity: null,
    description: "Skull shirt from the punk collection",
    collection: "punk",
  },
  {
    type: "torso",
    category: "shirt",
    renderOptions: {},
    name: "stripe shirt",
    price: 2000000000,
    quantity: null,
    description: "Stripe shirt from the artist collection",
    collection: "artist",
  },
  {
    type: "feet",
    category: "feet",
    renderOptions: {},
    name: "blue slip ons",
    price: 2000000000,
    quantity: null,
    description: "Blue slip ons from the snorkel collection",
    collection: "snorkel",
  },
  {
    type: "feet",
    category: "feet",
    renderOptions: {},
    name: "boots",
    price: 2000000000,
    quantity: null,
    description: "Boots from the cowboy collection",
    collection: "cowboy",
  },
  {
    type: "feet",
    category: "feet",
    renderOptions: {},
    name: "casual shoes",
    price: 2000000000,
    quantity: null,
    description: "Casual shoes from the banker collection",
    collection: "banker",
  },
  {
    type: "feet",
    category: "feet",
    renderOptions: {},
    name: "dress shoes",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "feet",
    category: "feet",
    renderOptions: {},
    name: "pink slip ons",
    price: 2000000000,
    quantity: null,
    description: "Pink slip ons from the swimmer collection",
    collection: "swimmer",
  },
  {
    type: "feet",
    category: "feet",
    renderOptions: {},
    name: "sneakers",
    price: 2000000000,
    quantity: null,
    description: "Sneakers from the grunge collection",
    collection: "grunge",
  },
  {
    type: "feet",
    category: "shoes",
    renderOptions: {},
    name: "goth boots",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "feet",
    category: "shoes",
    renderOptions: {},
    name: "rock star boots",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
  {
    type: "feet",
    category: "shoes",
    renderOptions: {},
    name: "witch boots",
    price: 2000000000,
    quantity: null,
    description: "",
    collection: "",
  },
];
