// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

import { ReactNode } from 'react';
import { AccessoryDesigner, AccessoryMetadata } from '../types/accessoryTypes';
import { SuiLogo } from '../components/Images/Logos/SuiLogo';

export const designerToPartnerLogo: Record<AccessoryDesigner, ReactNode> = {
	'mysten-labs': <SuiLogo />,
};

// Accessories lists names should match the names of the SVG files in the assets folder
export const accessories: AccessoryMetadata[] = [
	{
		type: 'head',
		category: 'hats',
		renderOptions: { showEars: false, showFin: false },
		name: 'baseball cap',
		price: 2000000000,
		quantity: null,
		description: 'Baseball cap from the punk collection',
		collection: 'punk',
		shopCategories: ['head-space'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'head',
		category: 'hats',
		renderOptions: { showEars: false, showFin: true },
		name: 'beanie',
		price: 2000000000,
		quantity: null,
		description: 'Beanie from the grunge collection',
		collection: 'grunge',
		shopCategories: ['head-space'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'head',
		category: 'hats',
		renderOptions: { showEars: false, showFin: true },
		name: 'beret',
		price: 2000000000,
		quantity: null,
		description: 'Beret from the artist collection',
		collection: 'artist',
		shopCategories: ['head-space', 'artist'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'head',
		category: 'hats',
		renderOptions: { showEars: false, showFin: true },
		name: 'bowler hat',
		price: 2000000000,
		quantity: null,
		description: 'Bowler hat from the banker collection',
		collection: 'banker',
		shopCategories: ['head-space'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'head',
		category: 'hats',
		renderOptions: { showEars: false, showFin: true },
		name: 'cowboy hat',
		price: 2000000000,
		quantity: null,
		description: 'Cowboy Hat from the cowboy collection',
		collection: 'cowboy',
		shopCategories: ['head-space'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'head',
		category: 'hats',
		renderOptions: { showEars: true, showFin: true },
		name: 'hair bow',
		price: 2000000000,
		quantity: null,
		description: 'Hair bow from the swimmer collection',
		collection: 'swimmer',
		shopCategories: ['head-space'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'head',
		category: 'hats',
		renderOptions: { showEars: true, showFin: true },
		name: 'halo',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['head-space'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'head',
		category: 'hats',
		renderOptions: { showEars: false, showFin: true },
		name: 'santa hat',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['head-space'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'head',
		category: 'wigs',
		renderOptions: { showEars: false, showFin: false },
		name: 'blonde wig',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['suifties'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'head',
		category: 'wigs',
		renderOptions: { showEars: false, showFin: false },
		name: 'curly wig',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['head-space', 'super-stars'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'head',
		category: 'wigs',
		renderOptions: { showEars: false, showFin: false },
		name: 'mohawk',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['head-space', 'cyber-frens', 'super-stars'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'head',
		category: 'hats',
		renderOptions: { showEars: false, showFin: true },
		name: 'wizard hat',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['head-space', 'sui-magicians'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'head',
		category: 'hats',
		renderOptions: { showEars: true, showFin: true },
		name: 'snorkel',
		price: 2000000000,
		quantity: null,
		description: 'Snorkel from the snorkel collection',
		collection: 'snorkel',
		shopCategories: ['under-the-sui'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'eyes',
		category: 'eyewear',
		renderOptions: { showEars: true, showFin: true },
		name: '8 bit glasses',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['sui-specs', 'cyber-frens'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'eyes',
		category: 'eyewear',
		renderOptions: { showEars: true, showFin: true },
		name: 'superhero mask',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['sui-specs', 'sui-magicians'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'eyes',
		category: 'eyewear',
		renderOptions: { showEars: true, showFin: true },
		name: 'xr goggles',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['cyber-frens', 'sui-specs'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'eyes',
		category: 'eyewear',
		renderOptions: { showEars: true, showFin: true },
		name: 'bug eyes',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['sui-specs', 'cyber-frens'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'body',
		category: 'body',
		renderOptions: {},
		name: 'apron',
		price: 2000000000,
		quantity: null,
		description: 'Apron from the artist collection',
		collection: 'artist',
		shopCategories: ['artist'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'body',
		category: 'body',
		renderOptions: {},
		name: 'cardigan',
		price: 2000000000,
		quantity: null,
		description: 'Cardigan from the grunge collection',
		collection: 'grunge',
		shopCategories: ['shirts-and-jackets'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'body',
		category: 'body',
		renderOptions: {},
		name: 'leather jacket',
		price: 2000000000,
		quantity: null,
		description: 'Leather jacket from the punk collection',
		collection: 'punk',
		shopCategories: ['shirts-and-jackets', 'cyber-frens'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'body',
		category: 'body',
		renderOptions: {},
		name: 'vest',
		price: 2000000000,
		quantity: null,
		description: 'Vest from the cowboy collection',
		collection: 'cowboy',
		shopCategories: ['shirts-and-jackets'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'back',
		category: 'capes',
		renderOptions: {},
		name: 'superhero cape',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: 'wizard',
		shopCategories: ['shirts-and-jackets', 'super-stars'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'body',
		category: 'body',
		renderOptions: {},
		name: 'wizard robe',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['shirts-and-jackets', 'sui-magicians'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'back',
		category: 'wings',
		renderOptions: {},
		name: 'wings',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['sui-magicians'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'legs',
		category: 'legs',
		renderOptions: {},
		name: 'white pants',
		price: 2000000000,
		quantity: null,
		description: 'White pants from the artist collection',
		collection: 'artist',
		shopCategories: ['artist', 'bottoms'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'legs',
		category: 'legs',
		renderOptions: {},
		name: 'bell bottoms',
		price: 2000000000,
		quantity: null,
		description: 'Bell bottoms from the grunge collection',
		collection: 'grunge',
		shopCategories: ['super-stars', 'bottoms', 'sui-magicians'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'legs',
		category: 'legs',
		renderOptions: {},
		name: 'blue jeans',
		price: 2000000000,
		quantity: null,
		description: 'Blue jeans from the punk collection',
		collection: 'punk',
		shopCategories: ['bottoms', 'cyber-frens'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'legs',
		category: 'legs',
		renderOptions: {},
		name: 'business slacks',
		price: 2000000000,
		quantity: null,
		description: 'Bussiness slacks from the banker collection',
		collection: 'banker',
		shopCategories: ['bottoms', 'cyber-frens'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'legs',
		category: 'legs',
		renderOptions: {},
		name: 'cutoffs',
		price: 2000000000,
		quantity: null,
		description: 'Cutoffs from the cowboy collection',
		collection: 'cowboy',
		shopCategories: ['bottoms', 'cyber-frens'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'legs',
		category: 'legs',
		renderOptions: {},
		name: 'swim trunks',
		price: 2000000000,
		quantity: null,
		description: 'Swim trunks from the snorkel collection',
		collection: 'snorkel',
		shopCategories: ['under-the-sui'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'legs',
		category: 'skirts',
		renderOptions: {},
		name: 'punk skirt',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['cyber-frens', 'bottoms', 'sui-magicians', 'super-stars'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'legs',
		category: 'skirts',
		renderOptions: {},
		name: 'rock star ruffle',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['suifties', 'bottoms'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'legs',
		category: 'skirts',
		renderOptions: {},
		name: 'superhero stars',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['super-stars', 'bottoms', 'sui-magicians'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'object',
		category: 'object',
		renderOptions: {},
		name: 'palette',
		price: 2000000000,
		quantity: null,
		description: 'Palette from the artist collection',
		collection: 'artist',
		shopCategories: ['artist', 'tchotchkes'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'object',
		category: 'object',
		renderOptions: {},
		name: 'brush',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['artist', 'tchotchkes'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'object',
		category: 'object',
		renderOptions: {},
		name: 'lasso',
		price: 2000000000,
		quantity: null,
		description: 'Lasso from the cowboy collection',
		collection: 'cowboy',
		shopCategories: ['tchotchkes'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'object',
		category: 'object',
		renderOptions: {},
		name: 'pencil',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['tchotchkes'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'object',
		category: 'object',
		renderOptions: {},
		name: 'magic wand',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['sui-magicians', 'tchotchkes'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'object',
		category: 'object',
		renderOptions: {},
		name: 'microphone',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['suifties', 'tchotchkes', 'super-stars'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'torso',
		category: 'shirt',
		renderOptions: {},
		name: 'business shirt',
		price: 2000000000,
		quantity: null,
		description: 'Business shirt from the banker collection',
		collection: 'banker',
		shopCategories: ['shirts-and-jackets'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'torso',
		category: 'shirt',
		renderOptions: {},
		name: 'cowboy shirt',
		price: 2000000000,
		quantity: null,
		description: 'Cowboy shirt from the cowboy collection',
		collection: 'cowboy',
		shopCategories: ['shirts-and-jackets'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'torso',
		category: 'shirt',
		renderOptions: {},
		name: 'swimsuit',
		price: 2000000000,
		quantity: null,
		description: 'Swimsuit from the swimmer collection',
		collection: 'swimmer',
		shopCategories: ['under-the-sui', 'bottoms'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'torso',
		category: 'shirt',
		renderOptions: {},
		name: 'heart shirt',
		price: 2000000000,
		quantity: null,
		description: 'Heart shirt from the grunge collection',
		collection: 'grunge',
		shopCategories: ['suifties', 'shirts-and-jackets'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'torso',
		category: 'shirt',
		renderOptions: {},
		name: 'lifeguard',
		price: 2000000000,
		quantity: null,
		description: 'Lifeguard from the snorkel collection',
		collection: 'snorkel',
		shopCategories: ['under-the-sui', 'shirts-and-jackets'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'torso',
		category: 'shirt',
		renderOptions: {},
		name: 'skull shirt',
		price: 2000000000,
		quantity: null,
		description: 'Skull shirt from the punk collection',
		collection: 'punk',
		shopCategories: ['cyber-frens', 'shirts-and-jackets', 'sui-magicians'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'torso',
		category: 'shirt',
		renderOptions: {},
		name: 'stripe shirt',
		price: 2000000000,
		quantity: null,
		description: 'Stripe shirt from the artist collection',
		collection: 'artist',
		shopCategories: ['artist', 'shirts-and-jackets'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'feet',
		category: 'feet',
		renderOptions: {},
		name: 'blue slip ons',
		price: 2000000000,
		quantity: null,
		description: 'Blue slip ons from the snorkel collection',
		collection: 'snorkel',
		shopCategories: ['under-the-sui', 'footwear'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'feet',
		category: 'feet',
		renderOptions: {},
		name: 'boots',
		price: 2000000000,
		quantity: null,
		description: 'Boots from the cowboy collection',
		collection: 'cowboy',
		shopCategories: ['footwear', 'artist'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'feet',
		category: 'feet',
		renderOptions: {},
		name: 'casual shoes',
		price: 2000000000,
		quantity: null,
		description: 'Casual shoes from the banker collection',
		collection: 'banker',
		shopCategories: ['footwear'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'feet',
		category: 'feet',
		renderOptions: {},
		name: 'dress shoes',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['footwear', 'cyber-frens'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'feet',
		category: 'feet',
		renderOptions: {},
		name: 'pink slip ons',
		price: 2000000000,
		quantity: null,
		description: 'Pink slip ons from the swimmer collection',
		collection: 'swimmer',
		shopCategories: ['under-the-sui', 'footwear'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'feet',
		category: 'feet',
		renderOptions: {},
		name: 'sneakers',
		price: 2000000000,
		quantity: null,
		description: 'Sneakers from the grunge collection',
		collection: 'grunge',
		shopCategories: ['footwear'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'feet',
		category: 'shoes',
		renderOptions: {},
		name: 'goth boots',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['footwear', 'cyber-frens'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'feet',
		category: 'shoes',
		renderOptions: {},
		name: 'rock star boots',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['footwear', 'suifties', 'super-stars'],
		designer: 'mysten-labs',

		version: 'v1',
	},
	{
		type: 'feet',
		category: 'shoes',
		renderOptions: {},
		name: 'witch boots',
		price: 2000000000,
		quantity: null,
		description: '',
		collection: '',
		shopCategories: ['footwear', 'sui-magicians'],
		designer: 'mysten-labs',

		version: 'v1',
	},
];
